"""add_photo_fields

Revision ID: 51a323559481
Revises: e98ff681d68e
Create Date: 2026-08-27 09:28:56.892333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51a323559481'
down_revision: Union[str, None] = 'e98ff681d68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.add_column('providers', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('providers', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('providers_user_id_fkey'), 'providers', type_='foreignkey')
    op.create_foreign_key(None, 'providers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('services', 'provider_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('services_provider_id_fkey'), 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'providers', ['provider_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('profile_photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo_url')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key(op.f('services_provider_id_fkey'), 'services', 'providers', ['provider_id'], ['id'])
    op.alter_column('services', 'provider_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.create_foreign_key(op.f('providers_user_id_fkey'), 'providers', 'users', ['user_id'], ['id'])
    op.alter_column('providers', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('providers', 'image_url')
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    # ### end Alembic commands ###
