"""Add confirmation fields

Revision ID: 5c7866720439
Revises: c38151ad74de
Create Date: 2025-05-08 21:39:02.812547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7866720439'
down_revision: Union[str, None] = 'c38151ad74de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_confirmation_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_confirmation_expires_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'is_email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_phone_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_phone_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'phone_confirmation_expires_at')
    op.drop_column('users', 'phone_confirmation_code')
    # ### end Alembic commands ###
