"""add is_identity_verified to user

Revision ID: 7152f4425ac3
Revises: 738e74ce13b8
Create Date: 2026-05-27 10:49:22.743706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7152f4425ac3'
down_revision: Union[str, None] = '738e74ce13b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_identity_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_identity_verified')
    # ### end Alembic commands ###
