"""make bvn optional and add id fields

Revision ID: 738e74ce13b8
Revises: 5c7866720439
Create Date: 2026-05-27 10:36:26.606221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738e74ce13b8'
down_revision: Union[str, None] = '5c7866720439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('id_number', sa.String(length=50), nullable=True))
    op.alter_column('users', 'bvn',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bvn',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.drop_column('users', 'id_number')
    op.drop_column('users', 'id_type')
    # ### end Alembic commands ###
