"""add reviews table

Revision ID: a408124920f4
Revises: b4a2e1dd866f
Create Date: 2025-05-04 02:21:50.210834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a408124920f4'
down_revision: Union[str, None] = 'b4a2e1dd866f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='reviews_booking_id_fkey'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name='reviews_customer_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name='reviews_provider_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey'),
    sa.UniqueConstraint('booking_id', name='reviews_booking_id_key')
    )
    # ### end Alembic commands ###
