"""Add confirmation fields

Revision ID: c38151ad74de
Revises: 0752d33f37d7
Create Date: 2025-05-08 19:19:19.315279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38151ad74de'
down_revision: Union[str, None] = '0752d33f37d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_confirmed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_phone_confirmed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('phone_confirmation_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_confirmation_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_confirmation_expires_at')
    op.drop_column('users', 'phone_confirmation_code')
    op.drop_column('users', 'is_phone_confirmed')
    op.drop_column('users', 'is_email_confirmed')
    # ### end Alembic commands ###
