"""add identity verification fields

Revision ID: e98ff681d68e
Revises: 7152f4425ac3
Create Date: 2026-05-27 15:00:31.799642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98ff681d68e'
down_revision: Union[str, None] = '7152f4425ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_photo_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('identity_status', sa.String(length=20), nullable=True))
    op.alter_column('users', 'id_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('users', 'bvn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bvn', sa.VARCHAR(length=11), autoincrement=False, nullable=True))
    op.alter_column('users', 'id_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('users', 'identity_status')
    op.drop_column('users', 'id_photo_url')
    # ### end Alembic commands ###
